services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 22010708
      MYSQL_DATABASE: home_energy_tracker
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql

volumes:
  db-data:
  mysql-logs:
